apiVersion: v1
kind: Service
metadata:
  labels:
    app: burguer-app
  name: client-burguer-app
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30790
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: burguer-app
  sessionAffinity: None