-- DDL


CREATE TABLE client (id integer primary key generated by default as identity, cpf varchar(255) NOT NULL UNIQUE, email varchar(255) NOT NULL, name varchar(255) NOT NULL);

CREATE INDEX idx_cpf ON client (cpf);
